"""
kpi_s3_synthetic_iride_elastic.py
=================================
Synthetic probe sui bucket S3 OVH IRIDE: misura la latenza di upload,
download e delete di un piccolo oggetto di test.

Copertura: TUTTI i 7 bucket (Framework + Ingestion, prod + e2etest).
Autorizzazione: CGI confermata in data 08/06/2026.

PRINCIPI DI MINIMA INVASIVITA':
  - Scrive in un PREFISSO DEDICATO '__monitoring/' (non si mescola coi dati reali).
  - Il file ha NOME UNIVOCO (timestamp + uuid) — non sovrascrive mai nulla.
  - Il file e' PICCOLISSIMO (~1 KB, contenuto fisso testuale identificabile).
  - Cleanup GARANTITO via try/finally (l'oggetto e' sempre cancellato).
  - Logging step-by-step: per ogni probe vedi upload/download/delete separatamente.

MODALITA' DRY-RUN ELASTIC:
  Stessa flag ELASTIC_ENABLED del .ini condiviso. Quando False, salva solo
  su file locale.
  NOTA: il "dry-run" riguarda SOLO Elasticsearch. Lo script SCRIVE sempre
  davvero su S3 (e' il punto del probe synthetic).

Cadenza suggerita: ogni 15 minuti (cron).
"""

import boto3
import os
import json
import time
import uuid
import configparser
import logging
import socket
from datetime import datetime, timezone
from botocore.config import Config as BotoConfig
from botocore.exceptions import ClientError

# ============================================================
# Logging
# ============================================================
logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

# ============================================================
# Config
# ============================================================
base_dir = os.path.dirname(os.path.abspath(__file__))
config_path = os.path.join(base_dir, 'service_bucket_folders_size_iride_elastic.ini')
config = configparser.ConfigParser()
config.read(config_path)

hostname = os.environ.get("HOSTNAME", socket.gethostname())

LOG_FILE_NAME = 'kpi_s3_synthetic_iride_elastic.log'
log_file = os.path.join(base_dir, LOG_FILE_NAME)

ELASTIC_ENABLED = config['CONFIG'].getboolean('ELASTIC_ENABLED', fallback=False)

es = None
MONITORING_INDEX = None
if ELASTIC_ENABLED:
    from elasticsearch import Elasticsearch
    MONITORING_URL = config['CONFIG']['MONITORING_URL']
    MONITORING_APIKEY = config['CONFIG']['MONITORING_APIKEY']
    MONITORING_VERIFY_CERTS = config['CONFIG'].getboolean('MONITORING_VERIFY_CERTS', fallback=True)
    MONITORING_INDEX = config['CONFIG'].get('SYNTHETIC_INDEX',
                                             fallback='kpi-iride-s3-synthetic.monitoring-default')
    es = Elasticsearch(
        [MONITORING_URL],
        headers={"Authorization": "ApiKey " + MONITORING_APIKEY},
        verify_certs=MONITORING_VERIFY_CERTS
    )
    logger.info(f"[CONFIG] Elasticsearch ABILITATO: {MONITORING_URL}")
else:
    logger.info("[CONFIG] Elasticsearch DISABILITATO (dry-run). Output solo su file locale.")

FRAMEWORK_CREDENTIALS = dict(config['IRIDE_FRAMEWORK_CREDENTIALS'])
INGESTION_CREDENTIALS = dict(config['IRIDE_INGESTION_CREDENTIALS'])

# ============================================================
# Constants
# ============================================================
MONITORING_PREFIX = "__monitoring/"

TEST_PAYLOAD = (
    b"IRIDE MONITORING SYNTHETIC PROBE\n"
    b"This file is a temporary monitoring artifact.\n"
    b"It is created and deleted automatically every probe run.\n"
    b"Safe to delete if found orphaned.\n"
    b"Generated by: kpi_s3_synthetic_iride_elastic.py\n"
    b"Authorized by CGI on 2026-06-08.\n"
    + b"=" * 200 + b"\n"
)

ORPHAN_AGE_HOURS = 24

# ============================================================
# Bucket da testare — TUTTI i 7 bucket (prod + e2etest)
# Autorizzazione CGI: 08/06/2026
# ============================================================
BUCKETS_TO_PROBE = [
    # (bucket_name, credentials, environment)
    # --- Framework (utente user-JtJyTKHwfFY2) ---
    ("cyberitaly-fmwk-container",            FRAMEWORK_CREDENTIALS, "prod"),
    ("cyberitaly-fmwk-output",               FRAMEWORK_CREDENTIALS, "prod"),
    ("cyberitaly-fmwk-output-e2etest",       FRAMEWORK_CREDENTIALS, "e2etest"),
    ("cyberitaly-fmwk-shared",               FRAMEWORK_CREDENTIALS, "prod"),
    ("cyberitaly-fmwk-shared-e2etest",       FRAMEWORK_CREDENTIALS, "e2etest"),
    # --- Ingestion (utente user-WWUWkDwYCdVz) ---
    ("cyberitaly-dingest-container",         INGESTION_CREDENTIALS, "prod"),
    ("cyberitaly-dingest-container-e2etest", INGESTION_CREDENTIALS, "e2etest"),
]

# ============================================================
# Helpers
# ============================================================
def create_log_entry(bucket_name, environment, status,
                     upload_ms=None, download_ms=None, delete_ms=None,
                     total_ms=None, error=None, object_key=None,
                     cleanup_required=False, cleanup_succeeded=None):
    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    entry = {
        "@timestamp": timestamp,
        "event_timestamp": timestamp,
        "bucket_name": bucket_name,
        "environment": environment,
        "platform": "iride",
        "service_provider_log": "iride_s3_synthetic",
        "response_status": status,
        "event_type": "kpi_s3_synthetic_probe",
        "hostname": hostname,
        "test_object_key": object_key or "",
        "test_payload_bytes": len(TEST_PAYLOAD),
        "cleanup_required": cleanup_required,
    }
    if cleanup_succeeded is not None:
        entry["cleanup_succeeded"] = cleanup_succeeded
    if upload_ms is not None:
        entry["upload_latency_ms"] = round(upload_ms, 2)
    if download_ms is not None:
        entry["download_latency_ms"] = round(download_ms, 2)
    if delete_ms is not None:
        entry["delete_latency_ms"] = round(delete_ms, 2)
    if total_ms is not None:
        entry["total_latency_ms"] = round(total_ms, 2)
    if error:
        entry["error_message"] = str(error)[:500]
    return entry


def write_log(log_entry):
    """Scrive su file locale e (se abilitato) indicizza su Elastic."""
    line = json.dumps(log_entry, ensure_ascii=False, separators=(',', ':'))
    with open(log_file, 'a') as f:
        f.write(line + '\n')

    if ELASTIC_ENABLED and es is not None:
        try:
            es.index(index=MONITORING_INDEX, body=log_entry)
        except Exception as e:
            logger.warning(f"[ES_FAIL] {type(e).__name__}: {e}")


def make_s3_client(credentials):
    return boto3.client(
        's3',
        **credentials,
        config=BotoConfig(read_timeout=30, connect_timeout=10, retries={'max_attempts': 1})
    )


def cleanup_orphans(s3, bucket_name):
    """Best-effort cleanup di vecchi file __monitoring/ orfani."""
    try:
        response = s3.list_objects_v2(Bucket=bucket_name, Prefix=MONITORING_PREFIX, MaxKeys=100)
        contents = response.get('Contents', [])
        if not contents:
            return 0

        now = datetime.now(timezone.utc)
        deleted = 0
        for obj in contents:
            age_hours = (now - obj['LastModified']).total_seconds() / 3600
            if age_hours > ORPHAN_AGE_HOURS:
                try:
                    s3.delete_object(Bucket=bucket_name, Key=obj['Key'])
                    deleted += 1
                    logger.info(f"[CLEANUP_ORPHAN] {bucket_name}: rimosso "
                                f"{obj['Key']} (age {age_hours:.1f}h)")
                except Exception as e:
                    logger.warning(f"[CLEANUP_FAIL] {obj['Key']}: {e}")
        return deleted
    except Exception as e:
        logger.warning(f"[CLEANUP_SKIP] {bucket_name}: {e}")
        return 0


# ============================================================
# Core probe
# ============================================================
def probe_bucket(bucket_name, credentials, environment):
    timestamp_str = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    unique_id = uuid.uuid4().hex[:12]
    object_key = f"{MONITORING_PREFIX}probe-{timestamp_str}-{unique_id}.txt"

    # Etichetta visiva per distinguere prod da e2etest nel log
    env_tag = "[PROD]" if environment == "prod" else "[E2E ]"
    logger.info(f"[PROBE] {env_tag} {bucket_name} → {object_key}")

    s3 = make_s3_client(credentials)
    upload_ms = download_ms = delete_ms = None
    uploaded = False
    delete_succeeded_in_main = False
    cleanup_succeeded = None
    overall_start = time.perf_counter()

    try:
        cleanup_orphans(s3, bucket_name)

        # --- UPLOAD ---
        t0 = time.perf_counter()
        s3.put_object(
            Bucket=bucket_name,
            Key=object_key,
            Body=TEST_PAYLOAD,
            ContentType='text/plain',
            Metadata={'purpose': 'synthetic-monitoring', 'safe-to-delete': 'true'}
        )
        upload_ms = (time.perf_counter() - t0) * 1000
        uploaded = True
        logger.info(f"  [UPLOAD]   ✓ {upload_ms:.2f} ms")

        # --- DOWNLOAD + integrity check ---
        t0 = time.perf_counter()
        response = s3.get_object(Bucket=bucket_name, Key=object_key)
        downloaded_body = response['Body'].read()
        download_ms = (time.perf_counter() - t0) * 1000

        if downloaded_body != TEST_PAYLOAD:
            logger.error(f"  [DOWNLOAD] ✗ integrity check FAILED")
            raise ValueError("Downloaded body mismatch — possibile corruption")
        logger.info(f"  [DOWNLOAD] ✓ {download_ms:.2f} ms (integrity OK)")

        # --- DELETE ---
        t0 = time.perf_counter()
        s3.delete_object(Bucket=bucket_name, Key=object_key)
        delete_ms = (time.perf_counter() - t0) * 1000
        uploaded = False
        delete_succeeded_in_main = True
        logger.info(f"  [DELETE]   ✓ {delete_ms:.2f} ms")

        # --- Esito complessivo ---
        total_ms = (time.perf_counter() - overall_start) * 1000
        if total_ms < 5000:
            status = "OK"
        elif total_ms < 15000:
            status = "SLOW"
        else:
            status = "FAIL"

        logger.info(f"[SALVATO] {bucket_name} status={status} total={total_ms:.2f}ms")
        entry = create_log_entry(
            bucket_name, environment, status,
            upload_ms=upload_ms, download_ms=download_ms,
            delete_ms=delete_ms, total_ms=total_ms,
            object_key=object_key,
            cleanup_required=False
        )
        write_log(entry)

    except ClientError as e:
        code = e.response.get('Error', {}).get('Code', '?')
        error_msg = f"{code}: {e}"
        logger.error(f"  [STEP_FAIL] {error_msg}")
        total_ms = (time.perf_counter() - overall_start) * 1000
        logger.info(f"[SALVATO] {bucket_name} status=FAIL total={total_ms:.2f}ms")
        entry = create_log_entry(
            bucket_name, environment, "FAIL",
            upload_ms=upload_ms, download_ms=download_ms,
            delete_ms=delete_ms, total_ms=total_ms,
            error=error_msg, object_key=object_key,
            cleanup_required=uploaded
        )
        write_log(entry)

    except Exception as e:
        error_msg = f"{type(e).__name__}: {e}"
        logger.error(f"  [STEP_FAIL] {error_msg}")
        total_ms = (time.perf_counter() - overall_start) * 1000
        logger.info(f"[SALVATO] {bucket_name} status=FAIL total={total_ms:.2f}ms")
        entry = create_log_entry(
            bucket_name, environment, "FAIL",
            upload_ms=upload_ms, download_ms=download_ms,
            delete_ms=delete_ms, total_ms=total_ms,
            error=error_msg, object_key=object_key,
            cleanup_required=uploaded
        )
        write_log(entry)

    finally:
        if uploaded:
            logger.warning(f"  [CLEANUP] tentativo finally su {object_key}...")
            try:
                s3.delete_object(Bucket=bucket_name, Key=object_key)
                cleanup_succeeded = True
                logger.info(f"  [CLEANUP] ✓ rimosso in finally")
            except Exception as e:
                cleanup_succeeded = False
                logger.error(f"  [CLEANUP] ✗ FAILED — orfano lasciato: {e}")
        elif delete_succeeded_in_main:
            logger.info(f"  [SUMMARY] upload/download/delete tutti OK — nessun residuo")


# ============================================================
# Main
# ============================================================
def main():
    logger.info(f"[AVVIO] kpi_s3_synthetic_iride_elastic — hostname={hostname}")
    prod_count = sum(1 for b in BUCKETS_TO_PROBE if b[2] == "prod")
    e2e_count = sum(1 for b in BUCKETS_TO_PROBE if b[2] == "e2etest")
    logger.info(f"[CONFIG] Bucket da probare: {len(BUCKETS_TO_PROBE)} "
                f"({prod_count} prod + {e2e_count} e2etest)")
    logger.info(f"[CONFIG] Payload: {len(TEST_PAYLOAD)} bytes")
    logger.info(f"[CONFIG] Prefisso dedicato: {MONITORING_PREFIX}")
    if not ELASTIC_ENABLED:
        logger.info("[CONFIG] >>> DRY-RUN MODE (no Elastic) <<<")
    logger.info("[CONFIG] NOTA: lo script SCRIVE realmente su S3 per misurare latenze")
    logger.info("[CONFIG] Autorizzazione CGI ricevuta in data 08/06/2026")
    logger.info("")

    # Statistiche aggregate per il riepilogo finale
    summary = {"OK": 0, "SLOW": 0, "FAIL": 0}

    for bucket_name, credentials, environment in BUCKETS_TO_PROBE:
        probe_bucket(bucket_name, credentials, environment)
        logger.info("")  # separatore visivo tra probe

    logger.info("[FINE] Tutti i probe completati")


if __name__ == '__main__':
    main()
